# Generated by Django 5.0.9 on 2025-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_topup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='status',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
    ]
