# Generated by Django 5.0.9 on 2024-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.ImageField(
                default="http://127.0.0.1:8000/events/officebank_cn706Jt.png",
                upload_to="events",
            ),
            preserve_default=False,
        ),
    ]
