# Generated by Django 5.0.9 on 2024-11-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_ticket"),
    ]

    operations = [
        migrations.RenameField(model_name="ticket", old_name="user", new_name="owner",),
    ]
