# Generated by Django 5.0.9 on 2024-11-09 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_prie_ticket_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendants",
            field=models.ManyToManyField(
                related_name="events",
                through="events.Ticket",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
