# Generated by Django 5.0.9 on 2024-11-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_attendants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
